### ISSUE TITLE
Falta documentación en el README

### ISSUE THREAD

**Issue by FranciscoNaveros** [hugobarzano/osl-computer-management#5]
Hola.
En el guión de prácticas se especifica lo siguiente:
En la documentación de este hito, que se integrará como el resto en el README.md del proyecto, se explicará por qué se ha elegido el sistema de test y de integración continua.

Además tienes que cumplir 3 objetivos:
    3 puntos: Configuración correcta de herramientas de construcción.
    5 puntos: Integración continua funcionando.
    2 puntos: Tests significativos y/o avance del proyecto en sí más allá de lo básico.

Quiero que me detalles en el README todos los pasos que has seguido para hacer esta práctica y me los justifiques.

**Comment by FranciscoNaveros** [comment]
En configuración correcta de herramientas de contrucción se refiero a que hagas un makefile (o cualquier otra opción que te parezca) para realizar todas las tareas con una sola orden. Por ejemplo, para pasar los test en local, que sea simplemente hacer make test y que esto llame a mocha test/test.js, python test.py o lo que sea que uses para pasar los test.

Este makefile irá aumentando con cada práctica.

**Comment by hugobarzano** [comment]
Acabo de añadir un fichero makefile como herramienta de contrución y he actualizado el README
