### ISSUE TITLE
Faltan objetivos

### ISSUE THREAD

**Issue by FranciscoNaveros** [hugobarzano/osl-computer-management#6]
Para esta segunda práctica tienes que tener el 80% de los ejercicios del tema 2 y el 80% de los objetivos del tema 2 y las sesiones 3 y 4. En caso contrario, tendras un cero.

**Comment by hugobarzano** [comment]
Acabo de actualizar el fichero de objetivos. Los ejercicios los subí a principios de la semana pasada.
